import { GuaranteeRecord } from '../types';

export const INITIAL_GUARANTEE_RECORDS: GuaranteeRecord[] = [
  {
    id: 'BG-REC-001',
    trackerRefNo: 'TRK-2026-0101',
    receivingDate: '2026-01-14',
    companyName: 'Apex Infrastructure Ltd',
    projectNumber: 'PRJ-8820',
    projectName: 'Kingston Coastal Expressway & Bridges',
    contractorType: 'Main Contractor',
    contractorName: 'Eastern Civil Engineering Corp',
    currency: 'USD',
    guaranteeType: 'Performance Bond (PB)',
    issuingBank: 'First Abu Dhabi Bank (FAB)',
    beneficiary: 'Apex Infrastructure Ltd',
    guaranteeReferenceNumber: 'FAB-PB-2026-9041',
    guaranteeValue: 4500000,
    fd: '2026-01-10',
    td: '2027-01-09',
    guaranteeStatus: 'Active',
    custodia: 'Central Treasury Safe Vault A',
    notes: 'Original hardcopy lodged in Vault A, Shelf 3, Envelope #45.',
    createdAt: '2026-01-14T09:30:00Z',
    updatedAt: '2026-01-14T09:30:00Z',
  },
  {
    id: 'BG-REC-002',
    trackerRefNo: 'TRK-2026-0102',
    receivingDate: '2026-02-05',
    companyName: 'Vertex Energy & Petrochem Co',
    projectNumber: 'PRJ-4412',
    projectName: 'Polymer Refinery Steam Turbine Unit 4',
    contractorType: 'EPC Contractor',
    contractorName: 'Hitachi Energy Plant Solutions',
    currency: 'EUR',
    guaranteeType: 'Advance Payment Guarantee (APG)',
    issuingBank: 'BNP Paribas',
    beneficiary: 'Vertex Energy & Petrochem Co',
    guaranteeReferenceNumber: 'BNP-APG-88129-EU',
    guaranteeValue: 7250000,
    fd: '2026-02-01',
    td: '2026-10-15',
    guaranteeStatus: 'Active',
    custodia: 'Finance Custody Locker #12',
    notes: 'Advance payment recovery linked to Milestones 1 to 4.',
    createdAt: '2026-02-05T11:00:00Z',
    updatedAt: '2026-02-05T11:00:00Z',
  },
  {
    id: 'BG-REC-003',
    trackerRefNo: 'TRK-2026-0103',
    receivingDate: '2026-03-20',
    companyName: 'Metroline Rail & Transit Group',
    projectNumber: 'PRJ-3109',
    projectName: 'Metro Green Line Signalling Modernization',
    contractorType: 'Subcontractor',
    contractorName: 'Alstom Transport Systems',
    currency: 'USD',
    guaranteeType: 'Retention Money Guarantee (RMG)',
    issuingBank: 'Standard Chartered Bank',
    beneficiary: 'Metroline Rail & Transit Group',
    guaranteeReferenceNumber: 'SCB-RMG-55210',
    guaranteeValue: 1200000,
    fd: '2026-03-15',
    td: '2026-10-05',
    guaranteeStatus: 'Active',
    custodia: 'Commercial Contracts Archive - Room 4',
    notes: 'Defect liability retention coverage.',
    createdAt: '2026-03-20T14:15:00Z',
    updatedAt: '2026-03-20T14:15:00Z',
  },
  {
    id: 'BG-REC-004',
    trackerRefNo: 'TRK-2026-0104',
    receivingDate: '2026-04-12',
    companyName: 'Gulf Horizon Contracting LLC',
    projectNumber: 'PRJ-9022',
    projectName: 'Marina High-Rise Tower A & B',
    contractorType: 'Joint Venture (JV) Partner',
    contractorName: 'Arabtec-Six Construct JV',
    currency: 'AED',
    guaranteeType: 'Bid Bond / Tender Guarantee (BB)',
    issuingBank: 'Emirates NBD',
    beneficiary: 'Gulf Horizon Contracting LLC',
    guaranteeReferenceNumber: 'ENBD-BB-339102',
    guaranteeValue: 3500000,
    fd: '2026-04-01',
    td: '2026-08-30',
    guaranteeStatus: 'Expired',
    custodia: 'HQ Document Control Safe',
    notes: 'Tender award finalized. Original bond awaiting release back to bank.',
    createdAt: '2026-04-12T10:00:00Z',
    updatedAt: '2026-08-31T10:00:00Z',
  },
  {
    id: 'BG-REC-005',
    trackerRefNo: 'TRK-2026-0105',
    receivingDate: '2026-05-18',
    companyName: 'Atlas Power Generation Corp',
    projectNumber: 'PRJ-1084',
    projectName: '500MW Solar Photovoltaic Substation',
    contractorType: 'Equipment / Material Supplier',
    contractorName: 'Sungrow Power Supply Co Ltd',
    currency: 'USD',
    guaranteeType: 'Maintenance / Warranty Bond',
    issuingBank: 'Citibank N.A.',
    beneficiary: 'Atlas Power Generation Corp',
    guaranteeReferenceNumber: 'CITI-WB-77291',
    guaranteeValue: 2800000,
    fd: '2026-05-01',
    td: '2028-05-01',
    guaranteeStatus: 'Active',
    custodia: 'Central Treasury Safe Vault B',
    notes: '2-year comprehensive inverter warranty bond.',
    createdAt: '2026-05-18T16:00:00Z',
    updatedAt: '2026-05-18T16:00:00Z',
  },
  {
    id: 'BG-REC-006',
    trackerRefNo: 'TRK-2026-0106',
    receivingDate: '2026-06-02',
    companyName: 'Oasis Marine & Port Operations',
    projectNumber: 'PRJ-7210',
    projectName: 'Deepwater Container Berth 5 Dredging',
    contractorType: 'Main Contractor',
    contractorName: 'Van Oord Dredging International',
    currency: 'EUR',
    guaranteeType: 'Performance Bond (PB)',
    issuingBank: 'Deutsche Bank AG',
    beneficiary: 'Oasis Marine & Port Operations',
    guaranteeReferenceNumber: 'DB-PB-994012',
    guaranteeValue: 6100000,
    fd: '2026-06-01',
    td: '2027-06-30',
    guaranteeStatus: 'Active',
    custodia: 'Central Treasury Safe Vault A',
    notes: 'Subject to annual extension clause upon mutual agreement.',
    createdAt: '2026-06-02T13:45:00Z',
    updatedAt: '2026-06-02T13:45:00Z',
  },
  {
    id: 'BG-REC-007',
    trackerRefNo: 'TRK-2026-0107',
    receivingDate: '2026-07-11',
    companyName: 'Pinnacle Civil Engineering Ltd',
    projectNumber: 'PRJ-6330',
    projectName: 'Wastewater Treatment Facility Phase 3',
    contractorType: 'Subcontractor',
    contractorName: 'Veolia Water Technologies',
    currency: 'GBP',
    guaranteeType: 'Advance Payment Guarantee (APG)',
    issuingBank: 'Barclays Corporate Banking',
    beneficiary: 'Pinnacle Civil Engineering Ltd',
    guaranteeReferenceNumber: 'BARC-APG-11029',
    guaranteeValue: 980000,
    fd: '2026-07-01',
    td: '2027-01-15',
    guaranteeStatus: 'Active',
    custodia: 'Finance Custody Locker #12',
    notes: 'Linked to biological filtration unit procurement.',
    createdAt: '2026-07-11T11:20:00Z',
    updatedAt: '2026-07-11T11:20:00Z',
  },
  {
    id: 'BG-REC-008',
    trackerRefNo: 'TRK-2026-0108',
    receivingDate: '2026-08-01',
    companyName: 'Apex Infrastructure Ltd',
    projectNumber: 'PRJ-8825',
    projectName: 'Airport Cargo Logistics Complex',
    contractorType: 'Main Contractor',
    contractorName: 'Consolidated Contractors Company (CCC)',
    currency: 'SAR',
    guaranteeType: 'Performance Bond (PB)',
    issuingBank: 'Saudi National Bank (SNB)',
    beneficiary: 'Apex Infrastructure Ltd',
    guaranteeReferenceNumber: 'SNB-PB-883011',
    guaranteeValue: 12500000,
    fd: '2026-08-01',
    td: '2027-08-01',
    guaranteeStatus: 'Active',
    custodia: 'Bank Custody - Escrow Locker',
    notes: 'Original stored directly in designated bank safe deposit with joint access.',
    createdAt: '2026-08-01T08:30:00Z',
    updatedAt: '2026-08-01T08:30:00Z',
  },
  {
    id: 'BG-REC-009',
    trackerRefNo: 'TRK-2026-0109',
    receivingDate: '2026-08-25',
    companyName: 'Delta Tech Facilities Management',
    projectNumber: 'PRJ-5011',
    projectName: 'District Cooling Chiller Overhaul',
    contractorType: 'Service Provider',
    contractorName: 'Johnson Controls Middle East',
    currency: 'USD',
    guaranteeType: 'Maintenance / Warranty Bond',
    issuingBank: 'HSBC Bank Middle East',
    beneficiary: 'Delta Tech Facilities Management',
    guaranteeReferenceNumber: 'HSBC-WB-40912',
    guaranteeValue: 450000,
    fd: '2026-08-20',
    td: '2026-09-30',
    guaranteeStatus: 'Active',
    custodia: 'HQ Document Control Safe',
    notes: 'Warranty period expires end of September. Renewal requested.',
    createdAt: '2026-08-25T14:00:00Z',
    updatedAt: '2026-08-25T14:00:00Z',
  },
  {
    id: 'BG-REC-010',
    trackerRefNo: 'TRK-2026-0110',
    receivingDate: '2026-09-02',
    companyName: 'Gulf Horizon Contracting LLC',
    projectNumber: 'PRJ-9040',
    projectName: 'Urban Skywalk Pedestrian Bridges',
    contractorType: 'Main Contractor',
    contractorName: 'Besix Contracting',
    currency: 'USD',
    guaranteeType: 'Bid Bond / Tender Guarantee (BB)',
    issuingBank: 'Standard Chartered Bank',
    beneficiary: 'Gulf Horizon Contracting LLC',
    guaranteeReferenceNumber: 'SCB-BB-772910',
    guaranteeValue: 1500000,
    fd: '2026-09-01',
    td: '2026-12-01',
    guaranteeStatus: 'Active',
    custodia: 'Central Treasury Safe Vault A',
    notes: 'Commercial evaluation stage underway.',
    createdAt: '2026-09-02T10:15:00Z',
    updatedAt: '2026-09-02T10:15:00Z',
  },
];
